### ISSUE TITLE
(Compatibility) issue, seems that the colors inside neovim with mosaic are wrong

### ISSUE THREAD

**Issue by denismaxim0v** [mosaic-org/mosaic#129] opened 2021-01-04 09:36 UTC
First issue of the year?  
I've noticed that mosaic breaks my neovim theme colors.
Expected:
![Screenshot from 2021-01-04 11-33-02](https://user-images.githubusercontent.com/11789381/103521126-3e9bb080-4e46-11eb-86d2-204b95fd767b.png)
Actual:
![Screenshot from 2021-01-04 11-33-28](https://user-images.githubusercontent.com/11789381/103521131-3f344700-4e46-11eb-9f77-836c23bad7c7.png)

[mosaic-3.log](https://github.com/mosaic-org/mosaic/files/5768926/mosaic-3.log)

**Comment by imsnif** [comment] 2021-01-04 13:29
Thanks! Could you attach a debug log to this?

**Comment by denismaxim0v** [comment] 2021-01-04 14:15
> Thanks! Could you attach a debug log to this?

Will do

**Comment by imsnif** [comment] 2021-01-22 09:34
@denismaxim0v - I want to work on this issue but am unable to reproduce it with the log file.
Could you help me out? I'd like for us to try to create a log file that when you `cat` inside mosiac, the issue is reproduced for you.
Could you:
1. Delete any existing log files in /tmp/mosaic
2. Start mosaic and reproduce the issue with just 1 pane
3. Exit mosaic immediately with `<ctrl-g> q` (this is important, because if you eg. exit nvim before exiting mosaic then the log file will also include stuff that happened afterwards)
4. cat the file in/out of mosaic and see that it is reproduced?

Once that works for you, could you also tell me what size terminal you reproduced this on? You can find that out with `tput cols` and `tput lines`.
Thanks!!

**Comment by denismaxim0v** [comment] 2021-01-22 09:46
Hmm, seems like the colors match now, do you think you could've fixed it somehow with one of your previous commits?

**Comment by imsnif** [comment] 2021-01-22 09:48
Definitely might be, there were some changes around properly clearing styles - could be related. So this works as intended now? Can we close the issue?

**Comment by denismaxim0v** [comment] 2021-01-22 09:48
Yes, I think so

**Closed** 2021-01-22 10:16 UTC
Labels: bug, compatibility

**Comment by imsnif** [comment] 2021-01-22 10:54
Awesome, glad to hear :)
